name: MyPy Check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Mypy Check
      uses: jpetrucciani/mypy-check@0.910
      with:
        args: "--ignore-missing-imports"